name: Python application

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #- name: Test with pytest
    #  run: |
    #    pytest -x -vv
    - name: Test with pylama
      run: |
        pylama
